// ✅ CORREGIDO: Importar IconDefinition desde el paquete correcto
import {
    faAndroid,
    faAngular,
    faApple,
    faBitbucket,
    faBitcoin,
    faChrome,
    faCss3Alt,
    faEdge,
    faEthereum,
    faFacebookF,
    faFirefox,
    faGithub,
    faGitlab,
    faGoogle,
    faHtml5,
    faInstagram,
    faInternetExplorer,
    faJava,
    faJs,
    faLaravel,
    faLinkedin,
    faLinux,
    faMagento,
    faNodeJs,
    faNpm,
    faOpera,
    faPaypal,
    faPhp,
    faPython,
    faReact,
    faSafari,
    faShopify,
    faStripe,
    faTiktok,
    faTwitter,
    faVuejs,
    faWhatsapp,
    faWindows,
    faWordpress,
    faYoutube
} from '@fortawesome/free-brands-svg-icons'
import {
    faAppleAlt,
    faArrowLeft,
    faArrowRight,
    faAtom,
    faAward,
    faBackward,
    faBars,
    faBell,
    faBellSlash,
    faBicycle,
    faBolt,
    faBook,
    faBookmark,
    faBookOpen,
    faBox,
    faBoxes,
    faBoxOpen,
    faBuilding,
    faBus,
    faCalendar,
    faCalendarAlt,
    faCamera,
    faCar,
    faChartBar,
    faChartLine,
    faChartPie,
    faCheck,
    faCheckCircle,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faCircleNotch,
    faCircle as faCircleSolid,
    faClock,
    faCloud,
    faCog,
    faCogs,
    faComment,
    faComments,
    faCompress,
    faCreditCard,
    faCrown,
    faDollarSign,
    faDolly,
    faDownload,
    faEdit,
    faEnvelope,
    faEuroSign,
    faExclamationCircle,
    faExclamationTriangle,
    faExpand,
    faFile,
    faFileExcel,
    faFilePdf,
    faFileWord,
    faFilm,
    faFilter,
    faFire,
    faFireAlt,
    faFlag,
    faFlask,
    faForward,
    faGem,
    faGift,
    faGraduationCap,
    faGripHorizontal,
    faGripVertical,
    faHandHolding,
    faHandshake,
    faHeadphones,
    faHeart,
    faHistory,
    faHome,
    faImage,
    faIndustry,
    faInfoCircle,
    faKey,
    faLeaf,
    faLink,
    faList,
    faLock,
    faMapMarkerAlt,
    faMaximize,
    faMedal,
    faMicrophone,
    faMicroscope,
    faMinimize,
    faMinus,
    faMoon,
    faMotorcycle,
    faMountain,
    faMusic,
    faPaintBrush,
    faPalette,
    faPallet,
    faPause,
    faPen,
    faPencilAlt,
    faPhone,
    faPlane,
    faPlay,
    faPlus,
    faQuestionCircle,
    faRedo,
    faRocket,
    faSatellite,
    faSave,
    faSearch,
    faSeedling,
    faShare,
    faShareAlt,
    faShield,
    faShip,
    faShippingFast,
    faShoppingBag,
    faShoppingCart,
    faSnowflake,
    faSort,
    faSortDown,
    faSortUp,
    faSpinner,
    faSquare,
    faStar,
    faStepBackward,
    faStepForward,
    faStop,
    faStore,
    faSun,
    faSync,
    faTable,
    faTag,
    faTags,
    faTh,
    faThermometerHalf,
    faThLarge,
    faThumbsDown,
    faThumbsUp,
    faTimes,
    faTimesCircle,
    faTint,
    faTools,
    faTrash,
    faTree,
    faTrophy,
    faTruck,
    faTruckLoading,
    faUmbrella,
    faUndo,
    faUnlink,
    faUnlock,
    faUpload,
    faUser,
    faUserMinus,
    faUserPlus,
    faUsers,
    faUsersCog,
    faUserTie,
    faVial,
    faVideo,
    faVideoSlash,
    faVolumeDown,
    faVolumeMute,
    faVolumeUp,
    faWarehouse,
    faWater,
    faWind,
    faWrench
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

// Mapeo de nombres de iconos Font Awesome a sus componentes
const iconMap: Record<string, typeof faBox> = {
  // Solid icons
  'fa-box': faBox,
  'fa-industry': faIndustry,
  'fa-wrench': faWrench,
  'fa-star': faStar,
  'fa-cog': faCog,
  'fa-tools': faTools,
  'fa-cogs': faCogs,
  'fa-truck': faTruck,
  'fa-users': faUsers,
  'fa-building': faBuilding,
  'fa-home': faHome,
  'fa-phone': faPhone,
  'fa-envelope': faEnvelope,
  'fa-map-marker-alt': faMapMarkerAlt,
  'fa-clock': faClock,
  'fa-search': faSearch,
  'fa-bars': faBars,
  'fa-times': faTimes,
  'fa-chevron-down': faChevronDown,
  'fa-chevron-right': faChevronRight,
  'fa-chevron-left': faChevronLeft,
  'fa-arrow-right': faArrowRight,
  'fa-arrow-left': faArrowLeft,
  'fa-check': faCheck,
  'fa-check-circle': faCheckCircle,
  'fa-times-circle': faTimesCircle,
  'fa-info-circle': faInfoCircle,
  'fa-exclamation-circle': faExclamationCircle,
  'fa-exclamation-triangle': faExclamationTriangle,
  'fa-question-circle': faQuestionCircle,
  'fa-plus': faPlus,
  'fa-minus': faMinus,
  'fa-edit': faEdit,
  'fa-trash': faTrash,
  'fa-save': faSave,
  'fa-download': faDownload,
  'fa-upload': faUpload,
  'fa-file': faFile,
  'fa-file-pdf': faFilePdf,
  'fa-file-excel': faFileExcel,
  'fa-file-word': faFileWord,
  'fa-image': faImage,
  'fa-video': faVideo,
  'fa-link': faLink,
  'fa-unlink': faUnlink,
  'fa-lock': faLock,
  'fa-unlock': faUnlock,
  'fa-key': faKey,
  'fa-shield': faShield,
  'fa-user': faUser,
  'fa-user-plus': faUserPlus,
  'fa-user-minus': faUserMinus,
  'fa-user-cog': faUsersCog,
  'fa-user-tie': faUserTie,
  'fa-chart-bar': faChartBar,
  'fa-chart-line': faChartLine,
  'fa-chart-pie': faChartPie,
  'fa-table': faTable,
  'fa-list': faList,
  'fa-th': faTh,
  'fa-th-large': faThLarge,
  'fa-grip-vertical': faGripVertical,
  'fa-grip-horizontal': faGripHorizontal,
  'fa-filter': faFilter,
  'fa-sort': faSort,
  'fa-sort-up': faSortUp,
  'fa-sort-down': faSortDown,
  'fa-sync': faSync,
  'fa-redo': faRedo,
  'fa-undo': faUndo,
  'fa-history': faHistory,
  'fa-calendar': faCalendar,
  'fa-calendar-alt': faCalendarAlt,
  'fa-bell': faBell,
  'fa-bell-slash': faBellSlash,
  'fa-comment': faComment,
  'fa-comments': faComments,
  'fa-share': faShare,
  'fa-share-alt': faShareAlt,
  'fa-heart': faHeart,
  'fa-thumbs-up': faThumbsUp,
  'fa-thumbs-down': faThumbsDown,
  'fa-flag': faFlag,
  'fa-bookmark': faBookmark,
  'fa-tag': faTag,
  'fa-tags': faTags,
  'fa-dollar-sign': faDollarSign,
  'fa-euro-sign': faEuroSign,
  'fa-credit-card': faCreditCard,
  'fa-shopping-cart': faShoppingCart,
  'fa-shopping-bag': faShoppingBag,
  'fa-store': faStore,
  'fa-box-open': faBoxOpen,
  'fa-boxes': faBoxes,
  'fa-pallet': faPallet,
  'fa-warehouse': faWarehouse,
  'fa-dolly': faDolly,
  'fa-truck-loading': faTruckLoading,
  'fa-shipping-fast': faShippingFast,
  'fa-hand-holding': faHandHolding,
  'fa-handshake': faHandshake,
  'fa-gift': faGift,
  'fa-award': faAward,
  'fa-medal': faMedal,
  'fa-trophy': faTrophy,
  'fa-crown': faCrown,
  'fa-gem': faGem,
  'fa-fire': faFire,
  'fa-bolt': faBolt,
  'fa-sun': faSun,
  'fa-moon': faMoon,
  'fa-cloud': faCloud,
  'fa-snowflake': faSnowflake,
  'fa-umbrella': faUmbrella,
  'fa-thermometer-half': faThermometerHalf,
  'fa-wind': faWind,
  'fa-tint': faTint,
  'fa-fire-alt': faFireAlt,
  'fa-water': faWater,
  'fa-mountain': faMountain,
  'fa-tree': faTree,
  'fa-leaf': faLeaf,
  'fa-seedling': faSeedling,
  'fa-apple-alt': faAppleAlt,
  'fa-car': faCar,
  'fa-bus': faBus,
  'fa-motorcycle': faMotorcycle,
  'fa-bicycle': faBicycle,
  'fa-plane': faPlane,
  'fa-ship': faShip,
  'fa-rocket': faRocket,
  'fa-satellite': faSatellite,
  'fa-atom': faAtom,
  'fa-flask': faFlask,
  'fa-vial': faVial,
  'fa-microscope': faMicroscope,
  'fa-book': faBook,
  'fa-book-open': faBookOpen,
  'fa-graduation-cap': faGraduationCap,
  'fa-pen': faPen,
  'fa-pencil-alt': faPencilAlt,
  'fa-paint-brush': faPaintBrush,
  'fa-palette': faPalette,
  'fa-music': faMusic,
  'fa-film': faFilm,
  'fa-camera': faCamera,
  'fa-video-slash': faVideoSlash,
  'fa-microphone': faMicrophone,
  'fa-headphones': faHeadphones,
  'fa-volume-up': faVolumeUp,
  'fa-volume-down': faVolumeDown,
  'fa-volume-mute': faVolumeMute,
  'fa-play': faPlay,
  'fa-pause': faPause,
  'fa-stop': faStop,
  'fa-forward': faForward,
  'fa-backward': faBackward,
  'fa-step-forward': faStepForward,
  'fa-step-backward': faStepBackward,
  'fa-expand': faExpand,
  'fa-compress': faCompress,
  'fa-maximize': faMaximize,
  'fa-minimize': faMinimize,
  'fa-spinner': faSpinner,
  'fa-circle-notch': faCircleNotch,
  'fa-circle': faCircleSolid,
  'fa-square': faSquare,
  // Brand icons
  'fa-facebook-f': faFacebookF,
  'fa-instagram': faInstagram,
  'fa-tiktok': faTiktok,
  'fa-youtube': faYoutube,
  'fa-twitter': faTwitter,
  'fa-linkedin': faLinkedin,
  'fa-whatsapp': faWhatsapp,
  'fa-google': faGoogle,
  'fa-apple': faApple,
  'fa-windows': faWindows,
  'fa-android': faAndroid,
  'fa-linux': faLinux,
  'fa-chrome': faChrome,
  'fa-firefox': faFirefox,
  'fa-safari': faSafari,
  'fa-edge': faEdge,
  'fa-opera': faOpera,
  'fa-internet-explorer': faInternetExplorer,
  'fa-github': faGithub,
  'fa-gitlab': faGitlab,
  'fa-bitbucket': faBitbucket,
  'fa-npm': faNpm,
  'fa-node-js': faNodeJs,
  'fa-php': faPhp,
  'fa-python': faPython,
  'fa-java': faJava,
  'fa-js': faJs,
  'fa-html5': faHtml5,
  'fa-css3-alt': faCss3Alt,
  'fa-react': faReact,
  'fa-vuejs': faVuejs,
  'fa-angular': faAngular,
  'fa-laravel': faLaravel,
  'fa-wordpress': faWordpress,
  'fa-shopify': faShopify,
  'fa-magento': faMagento,
  'fa-stripe': faStripe,
  'fa-paypal': faPaypal,
  'fa-bitcoin': faBitcoin,
  'fa-ethereum': faEthereum
}

export interface IconProps {
  name: string
  size?: 'xs' | 'lg' | 'sm' | '1x' | '2x' | '3x' | '4x' | '5x' | '6x' | '7x' | '8x' | '9x' | '10x'
  className?: string
  spin?: boolean
  pulse?: boolean
  rotation?: 90 | 180 | 270
  flip?: 'horizontal' | 'vertical' | 'both'
  fixedWidth?: boolean
}

export default function Icon({
  name,
  size = '1x',
  className = '',
  spin = false,
  pulse = false,
  rotation,
  flip,
  fixedWidth = false
}: IconProps) {
  const icon = iconMap[name]

  if (!icon) {
    console.warn(`Icono no encontrado: ${name}`)
    return null
  }

  return (
    <FontAwesomeIcon
      icon={icon}
      size={size}
      className={className}
      spin={spin}
      pulse={pulse}
      rotation={rotation}
      flip={flip}
      fixedWidth={fixedWidth}
    />
  )
}

// Helper para verificar si un icono existe
export function iconExists(name: string): boolean {
  return !!iconMap[name]
}

// Helper para obtener un icono por defecto si no existe
export function getIconOrDefault(name: string, defaultName: string = 'fa-circle'): string {
  return iconExists(name) ? name : defaultName
}